frp:
  image: zhanhao/frps
  ports:
    - "7000:7000/tcp"
    - "7500:7500/tcp"
    - "7000:7000/udp"
    - "5001:5001/tcp"
  volumes:
    - "/root/docker/frp-docker/config:/frp/config"
  restart: always

